### ISSUE TITLE
Add package to AUR

### ISSUE THREAD

**Issue by ptanmay143** [pdeljanov/infinality-remix#2]
Can we get this package on the Arch User Repository?

**Comment by pdeljanov** [comment]
Yup, that would be a good idea. However, I'm a bit short on time at the moment, and there are already up-to-date Infinality packages in the AUR (freetype2-infinality-ultimate, fontconfig-infinality-ultimate, cairo-infinality-ultimate) using a slightly different patch set. It looks like their patch set is also based off the original Infinality patch so I don't think there is any functional difference other than how we adapted the patch to version 2.9.* of FreeType and minor configuration changes.

I'll likely publish these packages with up-to-date patches to the AUR when the next upstream version of FreeType is released since it usually takes the *-infinality-ultimate packages a while to get updated.

**Comment by ronasimi** [comment]
cairo-infinality-ultimate and freetype2-infinality-ultimate are both flagged out of date, cairo has been flagged since 02/04/2019.  Your package works flawlessly, could you please reconsider adding this to the AUR?

**Comment by pdeljanov** [comment]
I took the time today to add these packages to the AUR. They build properly on my end when I install them via the AUR, but please give them a try as well. Thanks.

**Comment by ronasimi** [comment]
I just did a reinstall via the AUR packages  and there were no issues.

**Comment by pdeljanov** [comment]
Sounds good, I'll close this issue then. Cheers!
