### ISSUE TITLE
Lib32

### ISSUE THREAD

**Issue by rejedai** [pdeljanov/infinality-remix#4]
Will lib32 support?

**Comment by pdeljanov** [comment]
The PKGBUILD can be used to build either i686 or x86_64 packages, but it does not support multilib.

Since I don't use multilib on my system, I don't have any experience making multilib packages and wouldn't be able to easily test them. Therefore, I will probably not be adding any multilib packages myself any time soon.

Patches are welcome however, and I will keep this issue open if you or anyone else wants to contribute multilib support.
